### Numpy
- Numerical Python 
- One of the most efficient packages in python used for scientific calculations
- Faster than list
- homogenous data
- N-Dimensional array of data
- Stores the data as N Dimensional array and do calculations
- Installation :
    - pip install numpy-local machine/pc/system
    - import numpy-->notebook/idle


In [99]:
import numpy as np # 
#creating the array using tuples
t=np.array((1,2,3)) # row matrix
print(t)
print("......")
t2=np.array([(1,2,3),(4,5,6)]) # 2x3 matrix
print(t2)
np.__version__

[1 2 3]
......
[[1 2 3]
 [4 5 6]]


'1.18.1'

In [103]:
l=np.array([9,12,10,4]) # row matrix using a list
print(l)
print('.......')
l2=np.array([[5,8,9,90],[1,3,7,'hi']])
print(l2)
# homogenous data
l.dtype

[ 9 12 10  4]
.......
[['5' '8' '9' '90']
 ['1' '3' '7' 'hi']]


dtype('int32')

In [4]:
# pre defined functions in arrays
print(type(l2)) # checking the type of variable l2 # python function
print(l2.dtype) # checks the datatype of each element in the array
print(l2.shape) # no.of rows and columns
print(l2.size) # gives no.of elements present in the array
print(l2.itemsize) # each itemsize
print(l2.ndim) # dimension of the array
np.__version__ # checking the version of numpy

<class 'numpy.ndarray'>
<U11
(2, 4)
8
44
2


'1.18.1'

In [8]:
#Creating the array using range()
r=np.array(range(9)) # upper bound
print(r)
r2=np.array(range(2,13)) # both limits
print(r2)
r3=np.array(range(2,31,4)) # 
r3

[0 1 2 3 4 5 6 7 8]
[ 2  3  4  5  6  7  8  9 10 11 12]


array([ 2,  6, 10, 14, 18, 22, 26, 30])

### arange()
- which belongs to numpy module
- arange()
- arange().reshape()

In [104]:
# Creating the array using arange() method
print(np.arange(5))
print(np.arange(5,20))
print(np.arange(5,30,3)) #(start,stop,step_count)
print(np.arange(20,4,-3))
print(np.arange(4,2,-0.5)) # 4.0, 3.5, 3.0, 2.5, 2.0

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  8 11 14 17 20 23 26 29]
[20 17 14 11  8  5]
[4.  3.5 3.  2.5]


In [106]:
import numpy as np
ar=np.arange(20).reshape(5,4) # (1,20),(2,10),(5,4),(4,5),(20,1)
print(ar) # (row,col)
print('......')
ar2=np.arange(10,31).reshape(3,-1) # (10,30)-->30-->(1,21),(3,7),(7,3),(21,1)
print(ar2) #(3,7)
print('........')
ar3=np.arange(24).reshape(-3,6) #-->(1,24),(2,12),(4,6),(1,24),(6,4)
print(ar3)
print('......')
ar4=np.arange(10,40).reshape(5,6)
print(ar4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
......
[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]]
........
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
......
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]


In [108]:
# using linspace # 
print(np.linspace(10,30,7)) # partitioning the range with 3rd argument ->20/
print(np.linspace(3,10,4)) # both limits are inclusive  ->7/4=1.6

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.        ]
[ 3.          5.33333333  7.66666667 10.        ]


In [110]:
np.linspace(10,20,6) 

array([10., 12., 14., 16., 18., 20.])

In [112]:
# Creating the array with 0s,1s and full
o=np.ones((2,3)) # shape
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [113]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
f=np.full((3,2),8) #(shape,ele)
print(f)
print('....')
f.fill(5) # fun
f

[[8 8]
 [8 8]
 [8 8]]
....


array([[5, 5],
       [5, 5],
       [5, 5]])

In [118]:
st=np.array([[12,34,58],[9.3,8.5,60],['hi','hello','numpy']])
print(st)
print(type(st)) # data type of variable(python)
st.dtype # data type of each ele in st

[['12' '34' '58']
 ['9.3' '8.5' '60']
 ['hi' 'hello' 'numpy']]
<class 'numpy.ndarray'>


dtype('<U32')

In [119]:
print(np.diag(st)) # giving the diagonal elements of st

['12' '8.5' 'numpy']


In [121]:
np.eye(3) # creating identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [122]:
print(np.diag([1,7,3,6])) # creating the diagonal matrix

[[1 0 0 0]
 [0 7 0 0]
 [0 0 3 0]
 [0 0 0 6]]


### Random
- generates random values in a range
    - random.randint() # random value
        - random.randint(,)
        - random.randint(,,)
        - random.randint(,())
    - random.random(())
        - random matrix
    - random.(,)
    - random.randn(,)rand

In [131]:
r=np.random.randint(10) # 0 to 9
print(r)
r2=np.random.randint(10,40)
print(r2)
r3=np.random.randint(10,50,6) # generates 6 values in this range
print(r3)
r4=np.random.randint(10,100,(2,4)) # generate random array of size (2,4)
print(r4)
arn=np.random.randint(10,50,12).reshape(4,3) # reshaping the random matrix also
print(arn)

8
34
[45 33 20 31 45 25]
[[48 18 74 30]
 [91 11 52 39]]
[[47 39 46]
 [24 16 38]
 [14 19 13]
 [19 19 45]]


In [132]:
rn=np.random.random((3,2)) # 0 to 1 normal distribution values
rn

array([[0.34211025, 0.77163695],
       [0.8628363 , 0.35494811],
       [0.43384411, 0.46144355]])

In [134]:
rd=np.random.rand(2,3)
rd

array([[0.65831877, 0.8142859 , 0.38343238],
       [0.31051836, 0.05888223, 0.62686663]])

In [34]:
rdn=np.random.randn(3,2) # -1 to 1
rdn

array([[ 0.1312786 , -0.14944141],
       [-0.24337575,  0.13290865],
       [-0.08933607, -1.92870157]])

In [43]:
rnm=np.random.normal(10,5)
rnm

2.640338451504059

In [21]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

### Slicing
- Index based slicing
    - slicing is based on index
        - forward indexing
            - o to len(it)-1
        - backward indexing
            - -1 to -infinite
- Fancy indexing

In [136]:
import numpy as np
r5=np.random.randint(10,50,(4,5)) # 0 to 4--> 0 1 2 3
r5 # 0 to 4

array([[27, 33, 30, 43, 41],
       [31, 12, 36, 26, 15],
       [19, 16, 20, 27, 33],
       [48, 49, 26, 26, 35]])

In [137]:
r5[1:3,1:4]

array([[12, 36, 26],
       [16, 20, 27]])

In [138]:
r5[:] # representation of entire r5

array([[27, 33, 30, 43, 41],
       [31, 12, 36, 26, 15],
       [19, 16, 20, 27, 33],
       [48, 49, 26, 26, 35]])

In [139]:
r5[::] # full iterable

array([[27, 33, 30, 43, 41],
       [31, 12, 36, 26, 15],
       [19, 16, 20, 27, 33],
       [48, 49, 26, 26, 35]])

In [140]:
r5[1] # 2nd row in the array

array([31, 12, 36, 26, 15])

In [143]:
r5[1:]

array([[31, 12, 36, 26, 15],
       [19, 16, 20, 27, 33],
       [48, 49, 26, 26, 35]])

In [147]:
r5

array([[27, 33, 30, 43, 41],
       [31, 12, 36, 26, 15],
       [19, 16, 20, 27, 33],
       [48, 49, 26, 26, 35]])

In [148]:
r5[1:3,1:4]

array([[12, 36, 26],
       [16, 20, 27]])

In [145]:
# restriction on both rows and columns
r5[2:,:3] # ar[row,col]-->[3rd:last,first:2]

array([[19, 16, 20],
       [48, 49, 26]])

In [146]:
r5[1:,:2]

array([[31, 12],
       [19, 16],
       [48, 49]])

In [149]:
r5>30 # condition based slicing

array([[False,  True, False,  True,  True],
       [ True, False,  True, False, False],
       [False, False, False, False,  True],
       [ True,  True, False, False,  True]])

In [150]:
r5

array([[27, 33, 30, 43, 41],
       [31, 12, 36, 26, 15],
       [19, 16, 20, 27, 33],
       [48, 49, 26, 26, 35]])

In [43]:
r5>50 # elements in r5 will 

array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True,  True]])

In [151]:
r5[r5>40]

array([43, 41, 48, 49])

In [152]:
r5[r5>40].reshape(2,2)

array([[43, 41],
       [48, 49]])

In [154]:
r5[r5>30].sum()

349

In [155]:
r5

array([[27, 33, 30, 43, 41],
       [31, 12, 36, 26, 15],
       [19, 16, 20, 27, 33],
       [48, 49, 26, 26, 35]])

In [48]:
ar2=np.arange(10,40).reshape(6,-1)
ar2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [50]:
np.expand_dims(ar2,axis=3)

AxisError: axis 3 is out of bounds for array of dimension 3

In [26]:
help(np.expand_dims)

Help on function expand_dims in module numpy:

expand_dims(a, axis)
    Expand the shape of an array.
    
    Insert a new axis that will appear at the `axis` position in the expanded
    array shape.
    
    .. note:: Previous to NumPy 1.13.0, neither ``axis < -a.ndim - 1`` nor
       ``axis > a.ndim`` raised errors or put the new axis where documented.
       Those axis values are now deprecated and will raise an AxisError in the
       future.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int
        Position in the expanded axes where the new axis is placed.
    
    Returns
    -------
    res : ndarray
        Output array. The number of dimensions is one greater than that of
        the input array.
    
    See Also
    --------
    squeeze : The inverse operation, removing singleton dimensions
    reshape : Insert, remove, and combine dimensions, and resize existing ones
    doc.indexing, atleast_1d, atleast_2d, atleast_3d
    
    Exa

### Mathematical Operations

In [156]:
ar=np.arange(20).reshape(5,4)
ar2=np.array(range(8))
#3+4=7/2=3.5
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [161]:
m=np.random.randint(30,50,(5,4))
m

array([[30, 45, 40, 38],
       [32, 42, 31, 33],
       [35, 36, 41, 35],
       [40, 39, 37, 39],
       [41, 47, 36, 45]])

In [162]:
print(ar+m)
print('.......')
print(m-ar)
print('......')
print(ar*m)
print('......')
print(m/ar)
print('........')
print(np.min(m)) # minimum value in the random matrix m
print('........')
print(np.max(ar)) # max value 
print('......')
print(np.sum(ar))

[[30 46 42 41]
 [36 47 37 40]
 [43 45 51 46]
 [52 52 51 54]
 [57 64 54 64]]
.......
[[30 44 38 35]
 [28 37 25 26]
 [27 27 31 24]
 [28 26 23 24]
 [25 30 18 26]]
......
[[  0  45  80 114]
 [128 210 186 231]
 [280 324 410 385]
 [480 507 518 585]
 [656 799 648 855]]
......
[[        inf 45.         20.         12.66666667]
 [ 8.          8.4         5.16666667  4.71428571]
 [ 4.375       4.          4.1         3.18181818]
 [ 3.33333333  3.          2.64285714  2.6       ]
 [ 2.5625      2.76470588  2.          2.36842105]]
........
30
........
19
......
190


C:\Users\Dell\Desktop\anaconda\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


In [77]:
m2=np.random.randint(30,60,(4,4)) # (5,4) =(4,4)
m2

array([[59, 40, 57, 53],
       [34, 40, 51, 37],
       [59, 58, 38, 55],
       [43, 33, 51, 45]])

In [78]:
ar.dot(m2) # dot product of both matrices/arrays

array([[ 281,  255,  280,  282],
       [1061,  939, 1068, 1042],
       [1841, 1623, 1856, 1802],
       [2621, 2307, 2644, 2562],
       [3401, 2991, 3432, 3322]])

### Scientific Computation

In [163]:
print(np.mean(m)) # average of that array
print(np.std(m)) # random
print(np.median(ar))
print(ar.dot(m2))

38.1
4.603259714593562
9.5
[[ 281  255  280  282]
 [1061  939 1068 1042]
 [1841 1623 1856 1802]
 [2621 2307 2644 2562]
 [3401 2991 3432 3322]]


In [81]:
ar # 20-->sum of (middle 2 values)/2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Broadcasting
- applying a scalar value on array

In [164]:
print(ar+5) 
print(ar*4)
print(ar/3)# 0 to 19

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 0  4  8 12]
 [16 20 24 28]
 [32 36 40 44]
 [48 52 56 60]
 [64 68 72 76]]
[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]
 [4.         4.33333333 4.66666667 5.        ]
 [5.33333333 5.66666667 6.         6.33333333]]


### Logarithms and Exponentials

In [40]:
np.log(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [41]:
np.log(1)

0.0

In [42]:
np.log(10)

2.302585092994046

In [83]:
np.log(2)

0.6931471805599453

In [86]:
np.log2(2)

1.0

In [45]:
np.log2(10)

3.321928094887362

In [46]:
np.log([2,3,4])

array([0.69314718, 1.09861229, 1.38629436])

In [44]:
np.log(np.exp(1))

1.0

In [48]:
np.exp(2)

7.38905609893065

In [49]:
np.exp(2)-1

6.38905609893065

In [165]:
np.exp([2,3])

array([ 7.3890561 , 20.08553692])

### Vectorize functions
- The fuunctions of Numpy which can be applied on any variable

In [166]:
def greater(a,b):
    if a>b:
        return a
    else: return b
    
greater(4,10) # 

10

In [167]:
greater(20,6)

20

In [169]:
li=[23,4,19]
li2=[70,45,3]
greater(li,li2)

[70, 45, 3]

In [170]:
greater([5,3,1],[3,9,10])

[5, 3, 1]

In [171]:
sum(li)

46

In [172]:
sum(li2)

118

In [97]:
greater([67,23,45],[90,56,2])

[90, 56, 2]

In [98]:
v=np.vectorize(greater)
v([2,3,45],[98,34,2])

array([98, 34, 45])

In [48]:
help(v)

Help on vectorize in module numpy object:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns a single numpy array or a tuple of numpy
 |  arrays. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The

In [32]:
greater=[print(x) for x,y in zip([3,6,8],[2,9,5])if x>y]


3
8


In [5]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [11]:
r=range(1,13,3) # 12/6
for num in r:
    print(num,end=" ")

1 4 7 10 

In [8]:
r

range(1, 18)

In [70]:
st='apssdc'
st[0]

'a'

In [72]:
st[-1]

'c'

In [73]:
st[1:4] 

'pss'

In [74]:
st[0]

'a'

In [75]:
ord('a')

97

In [76]:
chr(97) in st

True

In [78]:
if chr(97) in st:
    print(chr(97)) # fancy indexing/slicing 

a


In [ ]:
data may be of any format-->
personal information:
    name,mbl,address,img,text,img,videos,audios...dle